language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
  licenses:
    - '.+'
before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.2"
    
sudo: required
install: true

before_script:
  - chmod +x gradlew

script:
- ./gradlew assembleRelease --stacktrace
